site_name: 'Inventory Service (Quarkus)'
site_description: 'A Quarkus-based backend service with CRUD operations'
docs_dir: 'docs'
repo_url: 'https://github.com/acme-corp/quarkus-inventory-service'
edit_uri: 'edit/main/docs/'

plugins:
  - techdocs-core
  
nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Database: database.md
  - Configuration: configuration.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md

